# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6907eae771cc52fc7a70e2300fff654a"
name = "ProductPulse AI"
application_url = "https://app-ppa.zuam.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_all_orders,read_customers,read_returns,read_inventory,read_locations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [ "https://app-ppa.zuam.dev/auth/callback" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
