# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "803894d3814cf8d9c9c99a345287b472"
application_url = "https://example.com"
embedded = true
name = "Product Pulse IA"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_returns"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
