ALTER TABLE "CreditLedgerEntry" ALTER COLUMN "amount" TYPE DOUBLE PRECISION USING "amount"::DOUBLE PRECISION;
ALTER TABLE "CreditLedgerEntry" ALTER COLUMN "balanceAfter" TYPE DOUBLE PRECISION USING "balanceAfter"::DOUBLE PRECISION;
ALTER TABLE "CreditLedgerEntry" ADD COLUMN "metadata" JSONB;
