import type {
  AppConceptExplanation,
  AppKnowledgeSnippet,
  AppScoreExplanation,
  AppScreenGuide,
  AppSettingExplanation,
} from "./types";

export const APP_KNOWLEDGE_LAST_UPDATED = "2026-05-26";

export const APP_KNOWLEDGE_SNIPPETS: AppKnowledgeSnippet[] = [
  {
    id: "overview-productpulse",
    topic: "overview",
    title: "What ProductPulse does",
    summary: "ProductPulse turns Shopify product, order, return, refund, review, and app source signals into product risk snapshots, diagnoses, evidence, watchlist activity, and app-owned actions.",
    body: "ProductPulse is a Shopify embedded app for ecommerce teams that need product-level guidance from fragmented product quality and commerce signals. The main workflows are QuickScan, Dashboard triage, Products/Candidates review, deep Product Diagnosis, Product Detail evidence review, Watchlist monitoring, Analytics, and Settings.",
    keywords: ["app", "overview", "what does productpulse do", "workflow", "product pulse", "help"],
    aliases: ["productpulse", "app", "application", "platform"],
    source: {
      documentTitle: "ProductPulse Overview",
      documentPath: "docs/app-knowledge/overview.md",
      section: "ProductPulse Overview",
      implementationRefs: ["app/routes/app._index.jsx", "app/routes/app.products.jsx", "app/routes/app.analytics.jsx"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "quickscan-process",
    topic: "quick_analysis",
    title: "QuickScan / Catalog Signal Scan",
    summary: "QuickScan is deterministic. It reads Shopify/catalog/order/return/refund data and connected CSV review ratings, then scores and stores product candidates without calling the AI model.",
    body: "QuickScan reads settings, extracts Shopify catalog and order-family data, optionally reads CSV review ratings, aggregates product signals, calculates deterministic scores, sorts by max(riskScore, productMomentum.score), and persists candidates that pass risk or momentum thresholds. It does not read full review text and does not call the model.",
    keywords: ["quickscan", "quick analysis", "catalog signal scan", "scan", "candidate", "deterministic"],
    aliases: ["quick analysis", "catalog scan", "fast scan", "catalog signal scan"],
    source: {
      documentTitle: "QuickScan / Catalog Signal Scan",
      documentPath: "docs/app-knowledge/quick-analysis.md",
      section: "Core flow",
      implementationRefs: ["app/lib/product-pulse-quick-scan.server.js:runShopifyQuickScan", "app/lib/product-pulse-quick-scan.server.js:buildQuickScanCandidates"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "deep-diagnosis-process",
    topic: "deep_analysis",
    title: "Deep Product Diagnosis",
    summary: "Deep diagnosis is a queued ProductPulse job that uses deterministic metrics plus AI synthesis to persist diagnoses, evidence, recommendations, snapshot updates, and score history.",
    body: "Deep diagnosis requires a stored ProductPulse product snapshot. The app queues a diagnosis job, prepares deterministic metrics and source snippets, uses AI for classification and synthesis, then saves ProductDiagnosis, updates ProductRiskSnapshot, records ProductScoreHistory, and may record watchlist activity.",
    keywords: ["deep analysis", "diagnosis", "product diagnosis", "ai diagnosis", "queued diagnosis"],
    aliases: ["deep diagnosis", "full diagnosis", "full analysis"],
    source: {
      documentTitle: "Deep Product Diagnosis",
      documentPath: "docs/app-knowledge/deep-analysis.md",
      section: "How it runs",
      implementationRefs: ["app/lib/product-pulse-jobs.server.js:queueProductDiagnosisForShop", "app/lib/product-pulse-diagnosis.server.js"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "candidate-selection",
    topic: "candidate_selection",
    title: "How candidates are selected",
    summary: "QuickScan candidates qualify by risk threshold or momentum threshold and are ranked by max(riskScore, productMomentum.score).",
    body: "A product qualifies as a candidate when its risk score is at least settings.risk.minimumScore or its Product Momentum score is at least settings.momentum.minimumScore. Defaults are risk minimum 18 and momentum minimum 70. Candidate score is max(riskScore, productMomentum.score).",
    keywords: ["candidate", "selection", "threshold", "risk threshold", "momentum threshold", "why product candidate"],
    aliases: ["candidate", "candidates", "product candidate"],
    source: {
      documentTitle: "Candidate Selection",
      documentPath: "docs/app-knowledge/candidate-selection.md",
      section: "Inclusion rules",
      implementationRefs: ["app/lib/product-pulse-quick-scan.server.js:scoreProductAggregate"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "scoring-overview",
    topic: "scoring",
    title: "Scores and metrics",
    summary: "ProductPulse scoring is deterministic for risk, confidence, evidence strength, impact, priority, coverage, revenue at risk, margin at risk, return/refund rates, review rating, negative review pressure, Product Momentum, and Product Momentum components.",
    body: "Risk is a heuristic 0-100 score built from capped return, review, sentiment, content, refund, variant, agreement, and recency components. Confidence evaluates evidence quality. Revenue at risk and margin at risk are estimated money exposures from returns, refunds, reviews, return/refund relationship, and basket context. Impact estimates money at risk. Priority blends risk, confidence, and log-normalized impact. Momentum measures commercial activity through velocity, growth, catalog share, trend consistency, and recency.",
    keywords: ["score", "risk", "confidence", "impact", "priority", "momentum", "coverage", "formula", "calculation", "revenue at risk", "margin at risk", "return rate", "refund rate", "review rating", "negative review rate", "negative review pressure", "velocity", "growth", "catalog share", "trend consistency", "recency"],
    aliases: ["scoring", "scores", "calculation", "formula"],
    source: {
      documentTitle: "ProductPulse Scoring",
      documentPath: "docs/app-knowledge/scoring.md",
      section: "ProductPulse Scoring",
      implementationRefs: ["app/lib/product-pulse-scoring.js", "app/lib/product-pulse-diagnosis.server.js:buildProductMomentum"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "watchlist-overview",
    topic: "watchlist",
    title: "Watchlist",
    summary: "The watchlist is an app-owned monitored product list capped at 50 products, with cadence, trigger, summary, and activity settings.",
    body: "Watchlist loads watched products, snapshots, change reports, active diagnosis jobs, score history, settings, and activity. It supports adding, pausing, resuming, and removing watched products. Alert recipient emails are not AI-safe output.",
    keywords: ["watchlist", "watch", "monitor", "alerts", "cadence", "activity"],
    aliases: ["watch list", "monitored products"],
    source: {
      documentTitle: "Watchlist",
      documentPath: "docs/app-knowledge/watchlist.md",
      section: "Watchlist",
      implementationRefs: ["app/lib/product-pulse-watchlist.server.js"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "dashboard-guide",
    topic: "dashboard",
    title: "Dashboard guide",
    summary: "Dashboard is the operational home for deciding where to start: active jobs, priority products, KPIs, points, and top issues.",
    body: "Read Dashboard by checking active jobs first, reviewing top priority products, using issue summaries for repeated patterns, and opening Product Detail before taking action. Dashboard is derived ProductPulse view data, not raw source data.",
    keywords: ["dashboard", "home", "start", "priority", "kpi", "top issues"],
    aliases: ["main page", "home screen"],
    source: {
      documentTitle: "Dashboard Guide",
      documentPath: "docs/app-knowledge/dashboard.md",
      section: "How to read it",
      implementationRefs: ["app/routes/app._index.jsx", "app/lib/product-pulse-jobs.server.js:getDashboardDataForShop"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "analytics-guide",
    topic: "analytics",
    title: "Analytics guide",
    summary: "Analytics is an aggregate ProductPulse view over snapshots, sources, actions, settings, latest diagnoses, active jobs, and score history.",
    body: "Analytics should be read as a portfolio-level summary. It can show risk distribution, average risk/confidence, top issues, source coverage, action counts, and trends. Use Product Detail for root-cause evidence.",
    keywords: ["analytics", "aggregate", "risk distribution", "trend", "source coverage", "portfolio"],
    aliases: ["analytics page", "reports"],
    source: {
      documentTitle: "Analytics Guide",
      documentPath: "docs/app-knowledge/analytics.md",
      section: "Analytics Guide",
      implementationRefs: ["app/routes/app.analytics.jsx", "app/lib/product-pulse-jobs.server.js:getAnalyticsDataForShop"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "settings-overview",
    topic: "settings",
    title: "Settings",
    summary: "Settings control risk thresholds, momentum inclusion, analysis lookback days, HTML injection style, and watchlist behavior.",
    body: "Settings include risk.minimumScore, risk.mediumThreshold, risk.highThreshold, momentum.minimumScore, analysis.lookbackDays, htmlStyle, and watchlist cadence/trigger/summary options. Bulk diagnosis queue submissions are unlimited by app settings.",
    keywords: ["settings", "configuration", "threshold", "lookback", "momentum threshold", "html style"],
    aliases: ["config", "configuration", "preferences"],
    source: {
      documentTitle: "Settings",
      documentPath: "docs/app-knowledge/settings.md",
      section: "Settings",
      implementationRefs: ["app/lib/product-pulse-settings.server.js", "app/routes/app.settings.jsx"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "recommended-actions-overview",
    topic: "recommended_actions",
    title: "Recommended actions",
    summary: "Recommendations are ProductPulse app-owned guidance records. They are not Shopify mutations and should not be treated as completed changes.",
    body: "Deep diagnosis can generate recommendations in ProductDiagnosis, and confirmed app mutations can create or update ProductAction rows. The AI assistant may explain, create, or update app-owned ProductPulse recommendations after confirmation, but it must not apply changes to Shopify.",
    keywords: ["recommendation", "recommended action", "product action", "action", "description", "seo", "qa review"],
    aliases: ["actions", "recommendations", "product actions"],
    source: {
      documentTitle: "Recommended Actions",
      documentPath: "docs/app-knowledge/recommended-actions.md",
      section: "Recommended Actions",
      implementationRefs: ["app/lib/product-pulse-diagnosis.server.js", "app/ai/appMutations"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "app-owned-actions",
    topic: "app_owned_actions",
    title: "App-owned actions and mutations",
    summary: "AI-confirmed mutations affect ProductPulse app data only. Shopify resources remain untouched.",
    body: "The assistant may propose, the user confirms, the backend validates, and ProductPulse saves app-owned records. Forbidden operations include Shopify product description, SEO, metafield, price, inventory, status, tag, variant, image, collection, or arbitrary Admin API mutations.",
    keywords: ["app-owned", "mutation", "confirm", "confirmation", "shopify mutation", "save action"],
    aliases: ["internal mutation", "app mutation", "app-owned mutation"],
    source: {
      documentTitle: "App-Owned Actions And Mutations",
      documentPath: "docs/app-knowledge/app-owned-actions.md",
      section: "App-Owned Actions And Mutations",
      implementationRefs: ["app/ai/actions", "app/ai/appMutations"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "product-detail-card-glossary",
    topic: "product_detail",
    title: "Product Detail cards and metrics",
    summary: "Product Detail cards have curated explanations for Overview, Recommended Actions, Product Momentum, Basket Context, return/refund cards, relationship timeline, Lift, and visible score components.",
    body: "Product Detail card knowledge explains what each visible card means, where it appears, which stored ProductPulse data it reads, which formula applies when documented, and which caveats matter. It covers Overview, Recommended Actions, Product Momentum components, Basket Context, Return pressure, Refund leakage, Evidence strength, Customer signals, Negative review pressure, relationship timeline, return/refund resolution, rates, and prediction/activity cards.",
    keywords: ["product detail", "card", "metric card", "overview", "recommended actions", "basket context", "relationship timeline", "lift", "return pressure", "refund leakage", "product momentum"],
    aliases: ["product page cards", "product detail cards", "metric cards", "card glossary"],
    source: {
      documentTitle: "Product Detail Cards",
      documentPath: "docs/app-knowledge/product-detail-cards.md",
      section: "Product Detail Card Glossary",
      implementationRefs: ["app/components/ProductPulseScreens.jsx", "app/ai/appKnowledge/productDetailCards.ts"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
  {
    id: "interaction-guidance",
    topic: "interaction_guidance",
    title: "Assistant interaction guidance",
    summary: "When a merchant request is broad or ambiguous, ProductPulse AI should guide with supported options and examples before creating action or mutation proposals.",
    body: "Interaction guidance covers ProductPulse product information, methodology explanations, watchlist options, creating app-owned product actions, editing app-owned product actions, and safe alternatives to direct Shopify mutations. Guidance is read-only and does not execute anything.",
    keywords: ["guidance", "what can i ask", "examples", "clarify", "next step", "create action", "edit action", "what can you do"],
    aliases: ["assistant guide", "examples", "what can you do", "next steps"],
    source: {
      documentTitle: "Interaction Guidance",
      documentPath: "docs/app-knowledge/interaction-guidance.md",
      section: "Guided assistant capabilities",
      implementationRefs: ["app/ai/appKnowledge/interactionGuidance.server.ts"],
    },
    confidence: "high",
    lastUpdated: APP_KNOWLEDGE_LAST_UPDATED,
  },
];

export const APP_CONCEPT_EXPLANATIONS: AppConceptExplanation[] = [
  {
    found: true,
    conceptName: "QuickScan",
    explanation: "QuickScan is the deterministic Catalog Signal Scan. It calculates product candidates from Shopify/product/order/return/refund data and connected CSV review ratings without calling the AI model.",
    relatedConcepts: ["Candidate", "Risk score", "Product Momentum", "Settings"],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "quickscan-process")?.source,
    confidence: "high",
  },
  {
    found: true,
    conceptName: "Deep Product Diagnosis",
    explanation: "Deep Product Diagnosis is a queued ProductPulse job that uses deterministic metrics plus AI synthesis to persist diagnosis, evidence, recommendations, snapshot updates, and score history.",
    relatedConcepts: ["ProductDiagnosis", "Evidence", "Recommended actions", "ProductAction"],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "deep-diagnosis-process")?.source,
    confidence: "high",
  },
  {
    found: true,
    conceptName: "Candidate",
    explanation: "A candidate is a stored ProductPulse snapshot that qualified during QuickScan by risk threshold or momentum threshold. It is not necessarily a bad product; it may need deeper diagnosis.",
    relatedConcepts: ["QuickScan", "ProductRiskSnapshot", "Product Momentum"],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "candidate-selection")?.source,
    confidence: "high",
  },
  {
    found: true,
    conceptName: "ProductAction",
    explanation: "ProductAction is a ProductPulse app-owned recommendation/action record visible in the product UI. It can store guidance such as description, SEO, QA, media, or internal review work, but the AI flow does not apply it to Shopify.",
    relatedConcepts: ["Recommended actions", "App-owned mutations", "Product detail"],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "recommended-actions-overview")?.source,
    confidence: "high",
  },
];

export const APP_SCORE_EXPLANATIONS: AppScoreExplanation[] = [
  {
    found: true,
    scoreName: "Risk score",
    meaning: "A deterministic 0-100 heuristic score for product risk.",
    logic: "Risk sums capped component families from returns, reviews, sentiment, content gap, refunds, variant concentration, source agreement, and recency.",
    formula: "riskScore = round(clamp(base + returns + reviews + sentiment + contentGap + refund + variant + agreementBonus + recencyBonus, 0, 100))",
    range: "0 to 100",
    inputs: ["Return rate and return pressure", "Refund rate and refund amount", "Review rating and negative review rate", "Sentiment and customer language", "Content issue count", "Variant concentration", "Source agreement", "Recent signals"],
    thresholds: [
      { label: "High risk", value: ">= 75", meaning: "Needs attention under default thresholds." },
      { label: "Watch / Medium", value: ">= 55", meaning: "Meaningful risk pattern." },
      { label: "Emerging", value: ">= 35", meaning: "Early risk signal." },
      { label: "Healthy / Low", value: "< 35", meaning: "No strong stored risk pattern." },
    ],
    interpretation: ["Higher means ProductPulse sees stronger evidence of product-level friction.", "Risk is not a probability.", "Settings can change the UI low/medium/high labels."],
    caveats: ["Missing sources and low sample sizes reduce confidence.", "QuickScan can flag risk before deep diagnosis explains cause."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Confidence",
    meaning: "How much ProductPulse trusts the evidence quality behind a score or diagnosis.",
    logic: "Confidence adds source coverage, independent source count, effective sample size, product match, agreement, and freshness, then subtracts penalties and applies caps.",
    formula: "confidenceRaw = coverage + independentSources + effectiveSample + productMatch + agreement + freshness - penalties",
    range: "0 to 99 after caps",
    inputs: ["Source count", "Independent source count", "Effective sample size", "Product match confidence", "Source agreement", "Freshness", "Missing-source penalties", "Low-sample penalties"],
    thresholds: [],
    interpretation: ["High confidence means stronger evidence support.", "Low confidence means the app may still have a signal, but supporting data is weak, sparse, stale, or incomplete."],
    caveats: ["Confidence is capped when samples or source independence are weak.", "It should not be read as model certainty."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Impact",
    meaning: "Estimated money at risk. It is not a 0-100 score.",
    logic: "Impact estimates confirmed refund loss, return processing cost, lost margin from returned units, projected future return loss, review conversion margin drag, and basket/bulk quantity exposure, then keeps the larger margin exposure when that is higher.",
    formula: "impactScore = estimatedImpact = roundMoney(max(observedLossAdjusted + projectedReturnLoss + reviewConversionMarginDrag + bulkQuantityExposure, marginAtRisk, confirmedRefundAmount, storedMarginAtRisk))",
    range: "Money value",
    inputs: ["Sold units", "Sales amount", "Return units/rate", "Refund units/amount", "Average unit revenue", "Review rating", "Negative review rate", "Margin rate", "Return processing cost", "Projection window", "Return/refund relationship", "Basket context"],
    thresholds: [],
    interpretation: ["Higher impact means the issue may matter more commercially.", "ProductPulse uses this in priority after log normalization."],
    caveats: ["Fallback margin rate is 45%.", "Fallback return processing cost is 8.", "Default projection is 90 days.", "External ad spend, taxes, chargebacks, and exceptions are not included unless modeled."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Revenue at risk",
    meaning: "Estimated gross revenue exposure from returned-unit exposure, projected excess returns, review conversion drag, relationship-adjusted refunds, and basket/bulk exposure.",
    logic: "ProductPulse calculates revenue exposure from projected lost revenue, return revenue exposure, review conversion drag, relationship-adjusted refund exposure, and basket/bulk revenue exposure, then keeps the larger of calculated exposure and any stored revenueAtRisk value.",
    formula: "revenueAtRisk = roundMoney(max(projectedLostRevenue + returnRevenueExposure + reviewConversionRevenueDrag + relationshipAdjustedRefundAmount + bulkRevenueExposure, storedRevenueAtRisk))",
    range: "Money value",
    inputs: ["Sold units", "Sales amount", "Average unit revenue", "Return units", "Refund amount", "Store return baseline", "Review rating", "Negative review rate", "Projection window", "Return/refund relationship", "Basket context"],
    thresholds: [],
    interpretation: ["Higher means more gross revenue exposure is associated with the product risk signals.", "It is revenue exposure, not guaranteed lost revenue."],
    caveats: ["Default projection window is 90 days.", "It includes estimated review conversion drag.", "Return/refund relationship and basket context are included when those summaries are available.", "It uses the maximum of calculated exposure and stored revenueAtRisk when present."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Margin at risk",
    meaning: "Estimated margin and cost exposure from projected returns, refund margin loss, return processing cost, review conversion drag, and basket/bulk quantity exposure.",
    logic: "ProductPulse calculates margin exposure from projected lost margin, refund margin loss, return processing cost, review conversion margin drag, and basket/bulk quantity exposure, then keeps the larger of calculated exposure and any stored marginAtRisk value.",
    formula: "marginAtRisk = roundMoney(max(projectedLostMargin + refundMarginLoss + returnProcessingCost + reviewConversionMarginDrag + bulkQuantityExposure, storedMarginAtRisk))",
    range: "Money value",
    inputs: ["Average unit revenue", "Return units", "Refund amount", "Margin rate", "Return processing cost", "Projected future units", "Excess return rate", "Review conversion drag", "Basket context"],
    thresholds: [],
    interpretation: ["Higher means more margin/cost exposure is associated with the product risk signals.", "This is closer to operational loss exposure than revenueAtRisk."],
    caveats: ["Fallback margin rate is 45%.", "Fallback return processing cost is 8.", "Basket/bulk quantity exposure is included when basket context is available.", "It uses the maximum of calculated exposure and stored marginAtRisk when present."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Estimated impact",
    meaning: "The money value used as ProductPulse impactScore.",
    logic: "Estimated impact takes the maximum of adjusted observed loss plus projected return/review drag and basket/bulk quantity exposure, margin at risk, confirmed refund amount, and stored marginAtRisk.",
    formula: "estimatedImpact = roundMoney(max(observedLossAdjusted + projectedReturnLoss + reviewConversionMarginDrag + bulkQuantityExposure, marginAtRisk, confirmedRefundAmount, storedMarginAtRisk))",
    range: "Money value",
    inputs: ["Confirmed refund amount", "Return processing cost", "Lost margin from returned units", "Projected return loss", "Review conversion margin drag", "Basket/bulk quantity exposure", "Margin at risk"],
    thresholds: [],
    interpretation: ["Higher impact raises ProductPulse priority after log normalization.", "Impact score is money, not a 0-100 score."],
    caveats: ["Impact low/high ranges use sample-size multipliers.", "It is an estimate based on available app and Shopify source data."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Return rate",
    meaning: "Percentage of sold units that were returned in the analysis window.",
    logic: "QuickScan divides return units by sold units and rounds to one decimal percentage point.",
    formula: "returnRate = round(returnUnits / soldUnits * 1000) / 10",
    range: "0% to 100%",
    inputs: ["Return units", "Sold units"],
    thresholds: [],
    interpretation: ["Higher return rate increases risk when it exceeds baseline and has enough sample support."],
    caveats: ["If sold units are zero, ProductPulse stores 0.", "Risk scoring uses a smoothed return rate against store baseline, not only the displayed percentage."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Return pressure",
    aliases: ["Returns anomaly", "Return friction"],
    meaning: "The Product Detail metric that summarizes customer friction from returned units and return/refund resolution state.",
    logic: "The visible card displays return pressure from return rate and return counts. Risk scoring uses a baseline-aware return anomaly multiplied by sample support. Purchase-context summaries can segment return pressure by bought-alone, bought-with-others, single-unit, multi-unit, bulk, and multi-variant orders.",
    formula: "returnPressure = returnedUnits / soldUnits; returnRiskWeight = returnAnomaly * sampleSupport",
    range: "Displayed as a rate/pressure signal; risk contribution is capped",
    inputs: ["Returned units", "Sold units", "Store average return rate", "Sample support", "Return/refund relationship buckets", "Purchase context segments"],
    thresholds: [],
    interpretation: ["Higher return pressure means more post-purchase friction.", "Return pressure is separate from refund dollars, which belong to Refund leakage and Financial exposure."],
    caveats: ["If sold units are zero, displayed pressure is 0.", "Multi-product basket ambiguity can reduce attribution confidence.", "It is not a standalone risk score."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "product-detail-card-glossary")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Refund rate",
    meaning: "Percentage of sold units that were refunded in the analysis window.",
    logic: "QuickScan divides refunded units by sold units and rounds to one decimal percentage point.",
    formula: "refundRate = round(refundUnits / soldUnits * 1000) / 10",
    range: "0% to 100%",
    inputs: ["Refund units", "Sold units"],
    thresholds: [
      { label: "High refund pressure", value: "soldUnits > 10 and refundRate > 20% and refundUnits >= 3", meaning: "Adds high refund pressure in risk scoring." },
      { label: "Monitor refund pressure", value: "refundUnits >= 3 and refundRate >= 10%", meaning: "Shown as monitor-level refund pressure." },
    ],
    interpretation: ["Higher refund rate can increase refund risk and financial exposure.", "Refund rate is displayed as a percentage; scoring uses normalized/smoothed rates."],
    caveats: ["If sold units are zero, ProductPulse stores 0.", "Refund amount also affects financial impact."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Refund leakage",
    aliases: ["Refund pressure", "Refund loss"],
    meaning: "The Product Detail metric that summarizes how much sales value is leaking into refunds.",
    logic: "The visible card focuses on refund rate, refunded units, refund amount, and return/refund attribution. Risk scoring uses baseline-aware refund anomaly, refund amount impact, and high-pressure rules multiplied by refund support.",
    formula: "refundLeakage = refundedUnits / soldUnits; refundRiskWeight = (refundAnomaly + impact + pressure) * refundSupport",
    range: "Displayed as a rate/pressure signal; financial exposure is money",
    inputs: ["Refunded units", "Sold units", "Refund amount", "Store average refund rate", "Attributed refunds", "Unattributed refunds", "Refund support"],
    thresholds: [
      { label: "High refund pressure", value: "soldUnits > 10 and refundRate > 20% and refundUnits >= 3", meaning: "Risk scoring treats this as high refund pressure." },
      { label: "Monitor refund pressure", value: "refundUnits >= 3 and refundRate >= 10%", meaning: "Shown as monitor-level refund pressure." },
    ],
    interpretation: ["Higher refund leakage means refunds are taking a larger share of sales.", "Read it with attribution confidence and financial exposure."],
    caveats: ["Unattributed refunds are separated to avoid over-blaming one product.", "Refund leakage is money-focused; Return pressure is friction-focused."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "product-detail-card-glossary")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Review rating",
    meaning: "Average CSV review rating for the product in the analysis window.",
    logic: "QuickScan divides the CSV review rating sum by CSV review rating count and rounds to one decimal.",
    formula: "reviewRating = round(csvReviewRatingSum / csvReviewRatingCount * 10) / 10",
    range: "Usually 0 to 5",
    inputs: ["CSV review rating sum", "CSV review rating count"],
    thresholds: [],
    interpretation: ["Lower rating can increase review risk and review conversion drag.", "No reviews gives 0 in QuickScan metrics."],
    caveats: ["QuickScan uses CSV rating aggregates, not full review text.", "Connected review integrations may affect full diagnosis differently."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Negative review rate",
    meaning: "Percentage of CSV ratings counted as low/negative in the analysis window.",
    logic: "QuickScan divides CSV low rating count by CSV review rating count and rounds to one decimal percentage point.",
    formula: "negativeReviewRate = round(csvLowRatingCount / csvReviewRatingCount * 1000) / 10",
    range: "0% to 100%",
    inputs: ["CSV low rating count", "CSV review rating count"],
    thresholds: [],
    interpretation: ["Higher negative review rate can increase review risk and review conversion drag.", "It is a source signal, not a standalone diagnosis."],
    caveats: ["If review count is zero, ProductPulse stores 0.", "Risk scoring smooths and caps low samples."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "QuickScan candidate score",
    meaning: "Ranking score used to order QuickScan candidates.",
    logic: "QuickScan ranks candidates by the stronger of product risk and Product Momentum.",
    formula: "quickScanCandidateScore = max(riskScore, productMomentum.score)",
    range: "0 to 100",
    inputs: ["Risk score", "Product Momentum score"],
    thresholds: [
      { label: "Risk inclusion", value: "riskScore >= settings.risk.minimumScore", meaning: "Product qualifies by risk." },
      { label: "Momentum inclusion", value: "productMomentum.score >= settings.momentum.minimumScore", meaning: "Product qualifies by commercial momentum." },
    ],
    interpretation: ["A product can rank high because it is risky or because it has strong momentum.", "This is why a low-risk product can still appear as a candidate."],
    caveats: ["Defaults are minimum risk 18 and minimum momentum 70.", "Candidate score is for triage and persistence, not a separate risk model."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "candidate-selection")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Priority score",
    meaning: "A 0-100 blend that ranks where to focus first.",
    logic: "Priority combines risk, confidence, and log-normalized impact.",
    formula: "priorityScore = round(clamp(0.5 * riskScore + 0.25 * confidenceScore + 0.25 * normalizedLogImpactScore, 0, 100))",
    range: "0 to 100",
    inputs: ["Risk score", "Confidence score", "Estimated impact", "Default max reference impact 25000"],
    thresholds: [],
    interpretation: ["Higher priority means ProductPulse has a stronger blend of risk, evidence confidence, and commercial impact."],
    caveats: ["Priority can rank a moderate-risk product higher if impact is large.", "It is a triage score, not a financial forecast."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Product Momentum",
    meaning: "A 0-100 commercial activity signal for whether a product is gaining traction.",
    logic: "Momentum blends current velocity, growth, catalog share, trend consistency, and recency, then applies caps for low volume, new products, or inventory constraints.",
    formula: "momentum = 0.35 * currentVelocity + 0.25 * growth + 0.20 * catalogShare + 0.15 * trendConsistency + 0.05 * recency",
    range: "0 to 100",
    inputs: ["Last 7/14/30 day sales", "Previous 30/90 day sales", "Weekly buckets", "Catalog distribution", "Product age", "Inventory constraint"],
    thresholds: [
      { label: "Hot", value: ">= 80", meaning: "Strong commercial signal." },
      { label: "Rising", value: ">= 60", meaning: "Positive momentum." },
      { label: "Stable", value: ">= 40", meaning: "Moderate activity." },
      { label: "Cooling", value: ">= 20", meaning: "Soft or declining activity." },
      { label: "Low activity", value: "< 20", meaning: "Little recent activity." },
    ],
    interpretation: ["Momentum can keep a product in candidates even when risk is below the minimum risk threshold.", "70 or more qualifies for default momentum inclusion."],
    caveats: ["No last-30-day activity gives score 0.", "Very low unit volume caps the score.", "Inventory constraints cap confidence at 70."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Velocity",
    meaning: "The current Product Momentum component that measures how this product's last-30-day units and revenue rank against the catalog.",
    logic: "ProductPulse calculates units and revenue percentile ranks for the last 30 days, then blends them with more weight on units.",
    formula: "currentVelocity = clamp(0.65 * unitsVelocityScore + 0.35 * revenueVelocityScore, 0, 96)",
    range: "0 to 96 before Product Momentum weighting",
    inputs: ["Units last 30 days", "Revenue last 30 days", "Catalog units distribution", "Catalog revenue distribution"],
    thresholds: [],
    interpretation: ["Higher velocity means the product is currently selling strongly relative to the catalog.", "Velocity contributes 35% of Product Momentum."],
    caveats: ["If catalog distribution is missing, percentile rank falls back to a log-scaled volume score.", "Velocity is commercial activity, not product risk."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Growth",
    meaning: "The Product Momentum component that compares current 30-day activity against the previous 30 days.",
    logic: "Growth uses smoothed unit and revenue ratios, then maps the combined ratio through log2. New activity with no prior 30-day baseline uses a capped new-spike formula.",
    formula: "growthScore = clamp(50 + 28 * log2(combinedGrowthRatio), 0, 96)",
    range: "0 to 96 before Product Momentum weighting",
    inputs: ["Units last 30 days", "Units previous 30 days", "Revenue last 30 days", "Revenue previous 30 days"],
    thresholds: [],
    interpretation: ["Above 50 means current activity is stronger than the previous period.", "Growth contributes 25% of Product Momentum."],
    caveats: ["Unit ratios use +3 smoothing.", "Revenue ratios use +25 smoothing.", "New activity after no prior period is capped at 88."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Catalog share",
    aliases: ["Catalog position", "Share lift"],
    meaning: "The Product Momentum component that measures this product's current share or position inside the catalog.",
    logic: "When a catalog baseline exists, ProductPulse scores share lift against the previous 90-day baseline and blends it with current velocity. If not, it falls back to top-catalog percentile position or volume.",
    formula: "catalogShareScore = clamp(0.55 * liftScore + 0.45 * currentVelocity, 0, 96)",
    range: "0 to 96 before Product Momentum weighting",
    inputs: ["Product units last 30 days", "Store units last 30 days", "Product units previous 90 days", "Store units previous 90 days", "Catalog percentile"],
    thresholds: [],
    interpretation: ["Higher catalog share means the product is taking a stronger position in the store catalog.", "Catalog share contributes 20% of Product Momentum."],
    caveats: ["Missing catalog baseline falls back to catalog position or volume scoring.", "This is catalog-relative demand, not a risk signal."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Lift",
    aliases: ["Relationship lift", "Share lift", "Affinity lift"],
    meaning: "A baseline comparison ratio. It answers whether an observed relationship, affinity, or catalog share is stronger than normal.",
    logic: "ProductPulse uses lift in two documented places: product relationships compare observed co-purchase/customer-sequence rates with baseline rates, and Product Momentum Catalog share compares current catalog share with the previous baseline share.",
    formula: "relationshipLift = relationshipRate / baselineRate; shareLiftRatio = (productShareLast30 + 0.0001) / (productShareBaseline + 0.0001)",
    range: "Ratio, usually shown as x lift or x vs baseline",
    inputs: ["Attach rate", "Relationship rate", "Related product baseline rate", "Customer baseline rate", "Product share last 30 days", "Product share baseline"],
    thresholds: [
      { label: "Above baseline", value: ">= 1.05x", meaning: "The relationship appears more often than baseline." },
      { label: "Near baseline", value: "0.95x to 1.04x", meaning: "The relationship appears about as often as baseline." },
      { label: "Below baseline", value: "< 0.95x", meaning: "The relationship is weaker than baseline." },
    ],
    interpretation: ["Above 1x is stronger than baseline.", "High lift with low sample size is not enough by itself.", "Relationship lift is observational and not causal."],
    caveats: ["Lift is unavailable when baseline frequency is missing.", "Catalog share lift and product relationship lift use the same baseline-ratio idea but different inputs."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "product-detail-card-glossary")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Trend consistency",
    meaning: "The Product Momentum component that checks whether recent weekly sales are active and directionally consistent.",
    logic: "ProductPulse computes a linear-regression slope over the last four weekly unit buckets, normalizes it, then blends direction with active-week coverage.",
    formula: "trendConsistencyScore = clamp(0.58 * trendDirectionScore + 0.42 * activeWeekRatio * 100, 0, 100)",
    range: "0 to 100 before Product Momentum weighting",
    inputs: ["Weekly units last 4 weeks", "Active week count", "Average weekly units", "Linear regression slope"],
    thresholds: [],
    interpretation: ["Higher trend consistency means sales are both recent and directionally stable or improving.", "Trend consistency contributes 15% of Product Momentum."],
    caveats: ["Sparse weekly sales can reduce the score even if a single week spiked.", "It is based on unit buckets, not full causal demand analysis."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Recency",
    meaning: "A documented ProductPulse component used in Product Momentum, risk scoring, and evidence strength to reward newer sales or signals.",
    logic: "For Product Momentum, recency scores how recently the product sold and how much of current activity happened in the last 7 days. Risk and evidence strength also use recent signal units.",
    formula: "momentumRecency = clamp(base + recentShare * 10 + (unitsLast7Days >= 5 ? 4 : 0), 0, 96); riskRecencyBonus = clamp(recentSignalUnits / signalEventCount * 6 + (recentSignalUnits >= 3 ? 1.5 : 0), 0, 5)",
    range: "Momentum recency: 0 to 96; risk recency bonus: 0 to 5; evidence recency/freshness: 0 to 10",
    inputs: ["Last sale date", "Units last 7 days", "Units last 14 days", "Units last 30 days", "Recent signal units", "Signal event count"],
    thresholds: [
      { label: "Very recent sale", value: "<= 2 days", meaning: "Momentum recency base is 86." },
      { label: "Recent sale", value: "<= 7 days", meaning: "Momentum recency base is 78." },
      { label: "Stale but inside 30 days", value: "<= 30 days", meaning: "Momentum recency base is 38." },
    ],
    interpretation: ["Higher recency means the commercial or risk signal is current.", "Recency contributes 5% of Product Momentum and up to 5 points of risk bonus."],
    caveats: ["Recency is not one single persisted top-level score; it appears as several documented components.", "If signal/event counts are unavailable, recency falls back to available sales windows."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Negative review pressure",
    meaning: "The Product Detail insight that shows negative reviews as a share of connected reviews.",
    logic: "The visible Negative review pressure card displays negativeReviewRate with negative and total review counts. Internal review evidence bars can also use a composite reviewSignalValue.",
    formula: "negativeReviewPressure = negativeReviewRate = roundPercent(negativeReviewCount / reviewCount)",
    range: "0% to 100%",
    inputs: ["Negative review count", "Review count", "Average rating", "CSV critical rating count", "CSV rating risk"],
    thresholds: [
      { label: "Red insight tone", value: "negativeReviewRate >= 12%", meaning: "Product Detail renders the insight with stronger warning tone." },
    ],
    interpretation: ["Higher negative review pressure means connected review sentiment is worsening or already concentrated.", "It can act as an early warning before returns/refunds fully appear."],
    caveats: ["If review count is zero, the rate is 0.", "The visible card is not a standalone risk score; risk scoring uses smoothed review risk separately."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    scoreName: "Source coverage",
    meaning: "A weighted percentage of connected ProductPulse source families.",
    logic: "Coverage divides connected source weight by total source weight.",
    formula: "coverageScore = round((connectedWeight / totalWeight) * 100)",
    range: "0 to 100",
    inputs: ["Shopify products", "Shopify orders", "Shopify returns", "Judge.me reviews", "Chatme reviews", "CSV reviews", "Support tickets", "PDP questions"],
    thresholds: [
      { label: "Strong", value: ">= 75", meaning: "Good source coverage." },
      { label: "Partial", value: ">= 45", meaning: "Some important sources are connected." },
      { label: "Low", value: "< 45", meaning: "Many signals may be missing." },
    ],
    interpretation: ["Higher coverage makes ProductPulse explanations more reliable.", "Low coverage means absence of evidence should be treated carefully."],
    caveats: ["Coverage is source availability, not product health.", "Some future source families may be unavailable in a shop."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "scoring-overview")?.source,
    confidence: "high",
  },
];

export const APP_SCREEN_GUIDES: AppScreenGuide[] = [
  {
    found: true,
    screenName: "Dashboard",
    purpose: "Operational home for deciding where to start.",
    dataShown: ["Priority products", "KPIs", "Active scan and diagnosis jobs", "Credit balance", "Top issues", "Latest diagnoses and actions"],
    howToRead: ["Check active jobs first.", "Review priority products by risk, confidence, impact, and momentum.", "Use top issues to spot repeated patterns.", "Open product detail before acting."],
    commonActions: ["Run scan", "Queue diagnosis", "Open product detail"],
    caveats: ["Dashboard data is derived view data.", "Products without snapshots may need QuickScan before diagnosis."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "dashboard-guide")?.source,
    confidence: "high",
  },
  {
    found: true,
    screenName: "Products",
    purpose: "Filterable product queue for full-analysis products and QuickScan candidates.",
    dataShown: ["Stored diagnoses", "QuickScan candidates", "Risk labels", "Watchlist state", "Active jobs", "Source coverage"],
    howToRead: ["Separate full diagnoses from candidates.", "Treat candidates as preliminary until deep diagnosis runs.", "Use filters to find high risk or high momentum products."],
    commonActions: ["Run fast product scan", "Bulk queue diagnoses", "Search Shopify products", "Add product candidate", "Add or remove watchlist item", "Mark resolved/unresolved", "Delete ProductPulse internal analysis"],
    caveats: ["Deleting internal analysis does not delete the Shopify product."],
    source: {
      documentTitle: "AI App Knowledge Discovery",
      documentPath: "docs/ai-app-knowledge-discovery.md",
      section: "Products",
      implementationRefs: ["app/routes/app.products.jsx"],
    },
    confidence: "high",
  },
  {
    found: true,
    screenName: "Product detail",
    purpose: "Product-level view for diagnosis, evidence, metrics, recommendations, action history, score history, and watchlist state.",
    dataShown: ["Current snapshot", "ProductActions", "Latest diagnosis", "Active diagnosis jobs", "Settings", "Watchlist item", "Score history", "Shopify product images"],
    howToRead: ["Start with risk/confidence/impact.", "Read evidence before acting on recommendations.", "Use action history to understand what ProductPulse has already recommended or saved."],
    commonActions: ["Queue diagnosis", "Review evidence", "Edit app-owned action", "Manage watchlist"],
    caveats: ["AI chat must update ProductPulse app-owned records only, not Shopify data."],
    source: {
      documentTitle: "AI App Knowledge Discovery",
      documentPath: "docs/ai-app-knowledge-discovery.md",
      section: "Product Detail",
      implementationRefs: ["app/routes/app.products_.$productId.jsx"],
    },
    confidence: "high",
  },
  {
    found: true,
    screenName: "Analytics",
    purpose: "Portfolio-level ProductPulse risk, impact, source, action, and trend view.",
    dataShown: ["Risk distribution", "Average risk/confidence", "Top issues", "Source coverage", "Action counts", "Risk and impact trends"],
    howToRead: ["Use it for aggregate patterns.", "Use Product Detail for root-cause evidence.", "Check source coverage before interpreting missing signals."],
    commonActions: ["Open products/issues", "Review source coverage", "Compare trends"],
    caveats: ["Some analytics are view-model aggregations instead of one exported formula."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "analytics-guide")?.source,
    confidence: "high",
  },
  {
    found: true,
    screenName: "Watchlist",
    purpose: "Monitor a capped set of important products.",
    dataShown: ["Watched products", "Current status", "Risk trend", "Recent activity", "Cadence/settings", "Active diagnosis jobs"],
    howToRead: ["Use it for products that deserve repeat monitoring.", "Paused products remain tracked but inactive.", "Activity explains what changed recently."],
    commonActions: ["Add product", "Pause", "Resume", "Remove", "Save settings", "Refresh/run watchlist process when available"],
    caveats: ["Watchlist is capped at 50 products."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "watchlist-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    screenName: "Settings",
    purpose: "Configure thresholds and evidence windows.",
    dataShown: ["Risk thresholds", "Momentum inclusion threshold", "Evidence lookback days", "HTML injection style", "Development-only mock dataset controls"],
    howToRead: ["Lower risk minimum keeps more candidates.", "Higher momentum threshold makes momentum inclusion stricter.", "Longer lookback uses more historical source data."],
    commonActions: ["Save settings", "Start mock dataset in development workflows"],
    caveats: ["Settings can change candidate volume and risk labels."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
];

export const APP_SETTING_EXPLANATIONS: AppSettingExplanation[] = [
  {
    found: true,
    settingName: "risk.minimumScore",
    meaning: "Minimum risk score for QuickScan risk-based candidate persistence.",
    allowedValues: ["0 to 90"],
    defaultValue: "18",
    effect: "QuickScan keeps products at or above this risk score unless momentum qualifies them separately.",
    caveats: ["Lower values create more candidates.", "This is separate from medium/high labels."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    settingName: "risk.mediumThreshold",
    meaning: "Risk score where the medium risk label starts.",
    allowedValues: ["Greater than minimum score", "No more than 95"],
    defaultValue: "55",
    effect: "Controls UI medium risk labeling.",
    caveats: ["Must be below high threshold."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    settingName: "risk.highThreshold",
    meaning: "Risk score where the high risk label starts.",
    allowedValues: ["Greater than medium threshold", "No more than 100"],
    defaultValue: "75",
    effect: "Controls UI high risk labeling.",
    caveats: ["Changing this does not change the underlying deterministic risk formula."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    settingName: "momentum.minimumScore",
    meaning: "Minimum Product Momentum score for momentum-based QuickScan inclusion.",
    allowedValues: ["0 to 100"],
    defaultValue: "70",
    effect: "QuickScan keeps products with momentum at or above this score even if risk is below the risk minimum.",
    caveats: ["This is why a low-risk product can still appear as a candidate."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    settingName: "analysis.lookbackDays",
    meaning: "How far back ProductPulse reads source data for QuickScan and full diagnosis.",
    allowedValues: ["10 to 365 days"],
    defaultValue: "60",
    effect: "Controls the evidence window for orders, returns, refunds, and connected reviews.",
    caveats: ["Longer windows can find older signals but may dilute recent changes."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "settings-overview")?.source,
    confidence: "high",
  },
  {
    found: true,
    settingName: "watchlist.scanCadenceDays",
    meaning: "How often watchlist scan logic is expected to run for monitored products.",
    allowedValues: ["1", "2", "3", "7", "14"],
    defaultValue: "3",
    effect: "Controls watchlist cadence.",
    caveats: ["Actual scheduling depends on the app process/cron setup."],
    source: APP_KNOWLEDGE_SNIPPETS.find((item) => item.id === "watchlist-overview")?.source,
    confidence: "high",
  },
];
