import type { AppProductDetailCardExplanation, AppKnowledgeSourceReference } from "./types";

const PRODUCT_DETAIL_CARD_SOURCE: AppKnowledgeSourceReference = {
  documentTitle: "Product Detail Cards",
  documentPath: "docs/app-knowledge/product-detail-cards.md",
  section: "Product Detail Card Glossary",
  implementationRefs: [
    "app/components/ProductPulseScreens.jsx",
    "app/lib/product-pulse-scoring.js",
    "app/lib/product-pulse-diagnosis.server.js",
  ],
};

const RELATIONSHIP_SOURCE: AppKnowledgeSourceReference = {
  documentTitle: "Product Relationship Intelligence metrics",
  documentPath: "docs/product-relationship-intelligence-metrics.md",
  section: "Relationship formulas",
  implementationRefs: [
    "app/lib/product-pulse-product-relationships.server.js",
    "app/components/ProductPulseScreens.jsx",
  ],
};

const PURCHASE_CONTEXT_SOURCE: AppKnowledgeSourceReference = {
  documentTitle: "Product Purchase Context Scoring Impact",
  documentPath: "docs/product-purchase-context-scoring-impact.md",
  section: "Return/refund segmentation",
  implementationRefs: [
    "app/lib/product-pulse-scoring.js",
    "app/lib/product-pulse-recalculation.server.js",
  ],
};

const SCORING_SOURCE: AppKnowledgeSourceReference = {
  documentTitle: "ProductPulse Scoring",
  documentPath: "docs/app-knowledge/scoring.md",
  section: "ProductPulse Scoring",
  implementationRefs: [
    "app/lib/product-pulse-scoring.js",
    "app/lib/product-pulse-diagnosis.server.js",
  ],
};

export const APP_PRODUCT_DETAIL_CARD_EXPLANATIONS: AppProductDetailCardExplanation[] = [
  {
    found: true,
    cardName: "Overview",
    aliases: ["product overview", "summary", "product summary", "product detail overview"],
    title: "Overview",
    subtitle: "Product-level summary of risk, confidence, impact, health, and current status.",
    purpose: "The Overview card is the entry point for reading one product. It combines the current ProductPulse snapshot, diagnosis state, key risk labels, impact values, and operational status so the merchant can decide whether to inspect evidence, recommendations, or history next.",
    whereShown: "Product Detail header and top summary area.",
    valueFormula: "overview = latest ProductRiskSnapshot + latest ProductDiagnosis + ProductAction/watchlist/job state",
    supportingFormulas: [
      "riskScore = round(clamp(base + returns + reviews + sentiment + contentGap + refund + variant + agreementBonus + recencyBonus, 0, 100))",
      "priorityScore = round(clamp(0.5 * riskScore + 0.25 * confidenceScore + 0.25 * normalizedLogImpactScore, 0, 100))",
      "estimatedImpact = roundMoney(max(observedLoss + projectedReturnLoss + reviewConversionMarginDrag, marginAtRisk, refundAmount, storedMarginAtRisk))",
    ],
    inputs: ["Latest product snapshot", "Latest diagnosis", "Score history", "Watchlist item", "Active jobs", "ProductAction records"],
    interpretation: [
      "Start here to understand whether the product has current risk, commercial momentum, or pending internal work.",
      "The Overview is a compact summary, not the full evidence report.",
      "Use the evidence and recommendations sections before deciding what to change inside ProductPulse.",
    ],
    caveats: [
      "If QuickScan has run but deep diagnosis has not, the Overview may show preliminary candidate data.",
      "The AI assistant must not treat Overview state as permission to mutate Shopify.",
    ],
    relatedMetrics: ["Risk score", "Confidence", "Estimated impact", "Priority score", "Product Momentum"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Recommended Actions",
    aliases: ["recommendations", "actions", "recommended fix", "ProductAction"],
    title: "Recommended Actions",
    subtitle: "App-owned actions ProductPulse suggests or stores for the product.",
    purpose: "Recommended Actions show ProductPulse app-owned guidance records. They can come from deep diagnosis recommendations or confirmed app-only mutations from the assistant. They are meant for review, editing, dismissal, completion, or later manual workflows.",
    whereShown: "Product Detail action/recommendation area and assistant action cards.",
    valueFormula: "recommendedActions = ProductDiagnosis.recommendations + ProductAction rows for the product",
    supportingFormulas: [
      "priority is derived from risk, confidence, impact, evidence strength, and action-specific rules",
      "action status is app-owned state such as open, reviewed, accepted, completed, or dismissed when supported",
    ],
    inputs: ["Diagnosis issues", "Evidence snippets", "ProductAction rows", "App-owned action status", "Product context", "User-confirmed assistant mutations"],
    interpretation: [
      "A recommended action is advice or internal ProductPulse work, not a completed Shopify change.",
      "Use its reason, expected result, and source evidence to decide whether it should be edited, dismissed, or marked reviewed.",
      "The assistant can create or update app-owned actions after confirmation, and those changes should appear in the Product Detail frontend.",
    ],
    caveats: [
      "Recommended Actions must not directly update Shopify product descriptions, SEO, prices, inventory, variants, images, or metafields from chat.",
      "Unsupported action types should be rejected rather than invented.",
    ],
    relatedMetrics: ["Recommended fix", "Priority score", "Evidence strength", "Main issue"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Product Momentum",
    aliases: ["momentum", "commercial signal"],
    title: "Product Momentum",
    subtitle: "Commercial signal based on recent velocity, growth, catalog position, trend consistency, and recency.",
    purpose: "Product Momentum answers whether the product matters commercially right now. It is separate from Product Risk so ProductPulse can distinguish high-risk products from fast-moving products that deserve attention because they are selling.",
    whereShown: "Product Detail commercial signal panel and product/candidate cards.",
    valueFormula: "momentum = 0.35 * currentVelocity + 0.25 * growth + 0.20 * catalogShare + 0.15 * trendConsistency + 0.05 * recency",
    supportingFormulas: [
      "currentVelocity = clamp(0.65 * unitsVelocityScore + 0.35 * revenueVelocityScore, 0, 96)",
      "growthScore = clamp(50 + 28 * log2(combinedGrowthRatio), 0, 96)",
      "catalogShareScore = clamp(0.55 * liftScore + 0.45 * currentVelocity, 0, 96)",
      "trendConsistencyScore = clamp(0.58 * trendDirectionScore + 0.42 * activeWeekRatio * 100, 0, 100)",
      "recencyScore = clamp(base + recentShare * 10 + (unitsLast7Days >= 5 ? 4 : 0), 0, 96)",
    ],
    inputs: ["Units and revenue in the last 7/14/30 days", "Previous 30/90 day baseline", "Weekly unit buckets", "Catalog distributions", "Last sale date", "Inventory constraints"],
    interpretation: [
      "80 or more is Hot, 60 to 79 is Rising, 40 to 59 is Stable, 20 to 39 is Cooling, below 20 is Low activity.",
      "A high Momentum product can deserve attention even when risk is low.",
      "Momentum is commercial traction, not customer dissatisfaction.",
    ],
    caveats: [
      "No last-30-day sales usually produces zero momentum.",
      "Low volume, young products, and inventory constraints can cap the score or confidence.",
    ],
    relatedMetrics: ["Velocity", "Growth", "Catalog share", "Trend consistency", "Recency"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Velocity",
    aliases: ["current velocity", "sales velocity"],
    title: "Velocity",
    subtitle: "Current sales strength relative to the catalog.",
    purpose: "Velocity explains how strongly the product is selling right now compared with other products in the store, using both units and revenue.",
    whereShown: "Product Momentum component breakdown.",
    valueFormula: "currentVelocity = clamp(0.65 * unitsVelocityScore + 0.35 * revenueVelocityScore, 0, 96)",
    supportingFormulas: [
      "unitsVelocityScore = percentileRank(unitsLast30Days, catalog.unitsLast30Distribution)",
      "revenueVelocityScore = percentileRank(revenueLast30Days, catalog.revenueLast30Distribution)",
    ],
    inputs: ["Units last 30 days", "Revenue last 30 days", "Catalog units distribution", "Catalog revenue distribution"],
    interpretation: ["Higher Velocity means this product is currently selling strongly relative to the catalog.", "Velocity contributes 35% of Product Momentum."],
    caveats: ["If catalog distribution is missing, ProductPulse falls back to log-scaled volume scoring.", "Velocity is not a risk signal."],
    relatedMetrics: ["Product Momentum", "Catalog share"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Growth",
    aliases: ["momentum growth", "sales growth"],
    title: "Growth",
    subtitle: "Current 30-day activity compared with the previous 30 days.",
    purpose: "Growth identifies whether recent units and revenue are accelerating, cooling, or staying stable versus the prior period.",
    whereShown: "Product Momentum component breakdown.",
    valueFormula: "growthScore = clamp(50 + 28 * log2(combinedGrowthRatio), 0, 96)",
    supportingFormulas: [
      "unitRatio = (unitsLast30Days + 3) / (unitsPrevious30Days + 3)",
      "revenueRatio = (revenueLast30Days + 25) / (revenuePrevious30Days + 25)",
      "no previous activity with current activity: growthScore = clamp(66 + 22 * volumeConfidence, 0, 88)",
    ],
    inputs: ["Units last 30 days", "Units previous 30 days", "Revenue last 30 days", "Revenue previous 30 days"],
    interpretation: ["Above 50 generally means the product is growing versus the previous period.", "Growth contributes 25% of Product Momentum."],
    caveats: ["Smoothing prevents tiny denominators from producing extreme growth.", "New spikes are capped to avoid over-ranking one-off activity."],
    relatedMetrics: ["Product Momentum", "Velocity"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Catalog share",
    aliases: ["catalog position", "share lift", "catalog share score"],
    title: "Catalog share",
    subtitle: "How important the product is relative to the wider catalog.",
    purpose: "Catalog share measures whether this product is taking a larger or smaller portion of store demand compared with its baseline or catalog rank.",
    whereShown: "Product Momentum component breakdown.",
    valueFormula: "catalogShareScore = clamp(0.55 * liftScore + 0.45 * currentVelocity, 0, 96)",
    supportingFormulas: [
      "productShareLast30 = unitsLast30Days / storeUnitsLast30Days",
      "productShareBaseline = unitsPrevious90Days / storeUnitsPrevious90Days",
      "shareLiftRatio = (productShareLast30 + 0.0001) / (productShareBaseline + 0.0001)",
      "liftScore = clamp(50 + 26 * log2(shareLiftRatio), 0, 96)",
    ],
    inputs: ["Product units last 30 days", "Store units last 30 days", "Product units previous 90 days", "Store units previous 90 days", "Catalog rank/percentile"],
    interpretation: ["Higher Catalog share means the product is taking a stronger position in the store catalog.", "Catalog share contributes 20% of Product Momentum."],
    caveats: ["When baseline data is missing, ProductPulse falls back to catalog rank or volume.", "Catalog share is commercial position, not quality risk."],
    relatedMetrics: ["Product Momentum", "Lift", "Velocity"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Trend consistency",
    aliases: ["trend", "weekly consistency"],
    title: "Trend consistency",
    subtitle: "Whether recent weekly sales are active and directionally consistent.",
    purpose: "Trend consistency prevents one isolated sales spike from looking like durable momentum by checking weekly activity and slope across the last four weekly unit buckets.",
    whereShown: "Product Momentum component breakdown and weekly momentum chart.",
    valueFormula: "trendConsistencyScore = clamp(0.58 * trendDirectionScore + 0.42 * activeWeekRatio * 100, 0, 100)",
    supportingFormulas: [
      "trendDirectionScore = clamp(50 + 70 * normalizedSlope, 0, 100)",
      "normalizedSlope = linearRegressionSlope(weeklyUnitsLast4Weeks) / max(averageWeeklyUnits, 1)",
      "activeWeekRatio = weeksWithUnits / 4",
    ],
    inputs: ["Last four weekly unit buckets", "Active week count", "Average weekly units", "Linear regression slope"],
    interpretation: ["Higher Trend consistency means sales are recent and directionally stable or improving.", "It contributes 15% of Product Momentum."],
    caveats: ["Sparse activity lowers the component even if one week was high.", "It is not a causal demand forecast."],
    relatedMetrics: ["Product Momentum", "Growth", "Recency"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Recency",
    aliases: ["recent activity", "freshness"],
    title: "Recency",
    subtitle: "How recently the product sold or produced evidence signals.",
    purpose: "Recency keeps ProductPulse focused on current commercial and risk signals. It is used in Product Momentum, risk scoring, and evidence strength with slightly different formulas.",
    whereShown: "Product Momentum breakdown, risk scoring, and evidence strength/freshness explanations.",
    valueFormula: "momentumRecency = clamp(base + recentShare * 10 + (unitsLast7Days >= 5 ? 4 : 0), 0, 96)",
    supportingFormulas: [
      "recentShare = unitsLast7Days / unitsLast30Days",
      "riskRecencyBonus = clamp(recentSignalUnits / signalEventCount * 6 + (recentSignalUnits >= 3 ? 1.5 : 0), 0, 5)",
      "evidenceFreshness = clamp(recentSignalUnits > 0 ? 4 + min(6, recentSignalUnits / signalEventCount * 8) : 0, 0, 10)",
    ],
    inputs: ["Last sale date", "Units last 7/14/30 days", "Recent signal units", "Signal event count"],
    interpretation: ["Higher Recency means the signal is current.", "In Product Momentum, Recency contributes 5% of the final score."],
    caveats: ["Recency is not one single persisted top-level score; it appears in multiple scoring contexts.", "If lastSaleAt is unknown, ProductPulse falls back to recent unit windows."],
    relatedMetrics: ["Product Momentum", "Risk score", "Evidence strength"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Lift",
    aliases: ["relationship lift", "share lift", "affinity lift"],
    title: "Lift",
    subtitle: "How much stronger a product relationship or catalog share is than its baseline.",
    purpose: "Lift is a ratio that compares an observed rate with a baseline rate. ProductPulse uses lift in product relationships and in Product Momentum catalog share scoring.",
    whereShown: "Product relationship timeline/table, relationship metric popovers, and Catalog share methodology.",
    valueFormula: "relationshipLift = relationshipRate / baselineRate",
    supportingFormulas: [
      "sameOrderLift = attachRate / relatedProductBaseRate",
      "beforeAfterLift = relationshipRate / customerBaseRateOfRelatedProduct",
      "shareLiftRatio = (productShareLast30 + 0.0001) / (productShareBaseline + 0.0001)",
      "catalogLiftScore = clamp(50 + 26 * log2(shareLiftRatio), 0, 96)",
    ],
    inputs: ["Attach rate", "Relationship rate", "Related product baseline rate", "Customer baseline rate", "Product/store share windows"],
    interpretation: [
      "Above 1x means the relationship or share is stronger than baseline.",
      "Around 1x means it appears about as often as baseline.",
      "Below 1x means it is weaker than baseline even if raw count exists.",
    ],
    caveats: [
      "Lift is unavailable when baseline frequency is missing or too small.",
      "High lift with tiny sample size should not be treated as reliable by itself.",
      "Relationship lift is observational and must not be described as causality.",
    ],
    relatedMetrics: ["Attach rate", "Relationship rate", "Catalog share", "Relationship strength"],
    source: RELATIONSHIP_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Product risk",
    aliases: ["risk", "risk card", "risk score"],
    title: "Product risk",
    subtitle: "Severity of product-level friction over time.",
    purpose: "Product risk shows how severe the product problem looks from stored evidence. It is the fastest way to decide whether the product itself needs attention before reading money, basket, or recommendation context.",
    whereShown: "Product Detail insight metric cards and product/candidate lists.",
    valueFormula: "riskScore = round(clamp(base + returns + reviews + sentiment + contentGap + refund + variant + agreementBonus + recencyBonus, 0, 100))",
    supportingFormulas: [
      "returns component capped at 25",
      "reviews component capped at 25",
      "refund component capped at 20",
      "recency bonus capped at 5",
    ],
    inputs: ["Returns", "Refunds", "Reviews", "Customer language", "Content gaps", "Variant concentration", "Source agreement", "Recent signals"],
    interpretation: ["A rising line means product risk is increasing.", "A falling line means the product is improving or evidence pressure is cooling."],
    caveats: ["Risk is a heuristic score, not a probability.", "Low confidence means the evidence may be incomplete."],
    relatedMetrics: ["Return pressure", "Refund leakage", "Negative review pressure", "Evidence strength"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Diagnosis confidence",
    aliases: ["confidence", "confidence score"],
    title: "Diagnosis confidence",
    subtitle: "Reliability of the diagnosis evidence.",
    purpose: "Diagnosis confidence tells whether the diagnosis is supported by enough source coverage, sample size, source agreement, freshness, and attribution quality to act on it.",
    whereShown: "Product Detail insight metric cards, diagnosis cards, and evidence report.",
    valueFormula: "confidenceRaw = coverage + independentSources + effectiveSample + productMatch + agreement + freshness - penalties",
    supportingFormulas: [
      "confidence is capped by source independence, sample size, data quality, and reconstruction state",
      "freshnessScore = clamp(recentSignalUnits > 0 ? 4 + min(6, recentSignalUnits / signalEventCount * 8) : 0, 0, 10)",
    ],
    inputs: ["Source coverage", "Independent sources", "Effective sample size", "Product match quality", "Source agreement", "Freshness", "Attribution quality", "Penalties"],
    interpretation: ["Higher confidence means ProductPulse has stronger support for the diagnosis.", "Use confidence to decide whether more data should be connected before acting."],
    caveats: ["Confidence is not model certainty.", "Unattributed refunds and incomplete basket context reduce confidence instead of over-blaming the product."],
    relatedMetrics: ["Evidence strength", "Source coverage", "Freshness", "Product match quality"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Financial exposure",
    aliases: ["financial exposure card", "money at risk", "impact"],
    title: "Financial exposure",
    subtitle: "Estimated money at risk from product friction.",
    purpose: "Financial exposure converts product signals into business impact while separating confirmed refunds from return-related risk and uncertainty.",
    whereShown: "Product Detail insight metric cards and evidence impact report.",
    valueFormula: "estimatedImpact = roundMoney(max(observedLoss + projectedReturnLoss + reviewConversionMarginDrag, marginAtRisk, refundAmount, storedMarginAtRisk))",
    supportingFormulas: [
      "observedLoss = refundAmount + returnProcessingCost + lostMarginFromReturnedUnits",
      "projectedReturnLoss = projectedFutureUnits * excessReturnRate * (avgUnitRevenue * marginRate + returnProcessingCost)",
      "reviewConversionMarginDrag = reviewConversionRevenueDrag * marginRate",
    ],
    inputs: ["Sales amount", "Sold units", "Return units", "Refund amount", "Average unit revenue", "Margin rate", "Return processing cost", "Review pressure"],
    interpretation: ["Higher financial exposure means the product issue may matter more commercially.", "A downward line usually means healthier exposure."],
    caveats: ["It is an estimate, not booked accounting loss.", "Default margin and return-processing assumptions are used when exact values are unavailable."],
    relatedMetrics: ["Estimated impact", "Revenue at risk", "Margin at risk", "Refund leakage"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Return pressure",
    aliases: ["returns anomaly", "return friction", "return pressure card"],
    title: "Return pressure",
    subtitle: "Product friction from returned units and return/refund resolution state.",
    purpose: "Return pressure focuses on customer friction: returned units, return-only cases, linked return+refund cases, exchanges, and pending return outcomes. It deliberately stays separate from refund dollars.",
    whereShown: "Product Detail insight metric cards, return evidence, and purchase-context scoring explanations.",
    valueFormula: "returnPressure = returnRate = returnedUnits / soldUnits",
    supportingFormulas: [
      "returnRiskWeight = returnAnomaly * sampleSupport",
      "returnAnomaly = storeAvgReturnRate > 0 ? max(0, min(25, ((returnRate / storeAvgReturnRate) - 1) * 14)) : min(22, returnRate * 1.2)",
      "purchase context segments include return rate when bought alone, with others, single-unit, multi-unit, bulk, and multi-variant",
    ],
    inputs: ["Returned units", "Sold units", "Store average return rate", "Return/refund relationship buckets", "Purchase context segments", "Sample support"],
    interpretation: ["A rising line means return-related friction is building.", "High return pressure can drive risk even before refund amount is large."],
    caveats: ["Return pressure is not the same as refund leakage.", "Multi-product basket ambiguity can reduce attribution confidence."],
    relatedMetrics: ["Return rate", "Return + refund resolution", "Refund leakage", "Product risk"],
    source: PURCHASE_CONTEXT_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Refund leakage",
    aliases: ["refund pressure", "refund leakage card", "refund loss"],
    title: "Refund leakage",
    subtitle: "Sales value leaking into refunds.",
    purpose: "Refund leakage highlights confirmed or attributed financial loss after purchase, split between refunds with returns, refunds without returns, and unattributed refunds.",
    whereShown: "Product Detail insight metric cards, return/refund resolution, and evidence impact report.",
    valueFormula: "refundLeakage = refundRate = refundedUnits / soldUnits",
    supportingFormulas: [
      "refundRiskWeight = (refundAnomaly + impact + pressure) * refundSupport",
      "refundAnomaly = storeAvgRefundRate > 0 ? max(0, min(20, ((refundRate / storeAvgRefundRate) - 1) * 11)) : min(18, refundRate)",
      "impact = min(15, log10(refundAmount + 1) * 4)",
    ],
    inputs: ["Refunded units", "Sold units", "Refund amount", "Store average refund rate", "Attributed/unattributed refund buckets", "Refund support"],
    interpretation: ["A rising line means refunds are taking a larger share of sales.", "Refund leakage matters most when refund amount and attribution quality are strong."],
    caveats: ["Unattributed refunds are tracked separately and should not be over-blamed on one product.", "Refund leakage is money-focused; return pressure is friction-focused."],
    relatedMetrics: ["Refund rate", "Financial exposure", "Return + refund resolution", "Revenue at risk"],
    source: PURCHASE_CONTEXT_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Evidence strength",
    aliases: ["evidence", "source support"],
    title: "Evidence strength",
    subtitle: "How broad and useful the supporting evidence is.",
    purpose: "Evidence strength helps merchants know how much support sits behind the diagnosis and whether more sources would improve confidence.",
    whereShown: "Product Detail insight metric cards, evidence report, and assistant evidence cards.",
    valueFormula: "evidenceStrengthScore = round(clamp(signalVolumeScore * 1.3 + independentSourceScore * 1.4 + sourceAgreementScore * 1.3 + recencyScore * 1.1, 0, 100))",
    supportingFormulas: [
      "coverageScore = round((connectedWeight / totalWeight) * 100)",
      "recencyScore = freshnessScore = clamp(recentSignalUnits > 0 ? 4 + min(6, recentSignalUnits / signalEventCount * 8) : 0, 0, 10)",
    ],
    inputs: ["Signal volume", "Independent source count", "Source agreement", "Freshness", "Connected source coverage"],
    interpretation: ["Higher evidence strength means the diagnosis is supported by broader or fresher evidence.", "It is support strength, not risk severity."],
    caveats: ["A low-risk product can still have high evidence strength.", "A high-risk product with low evidence strength may need more data before action."],
    relatedMetrics: ["Source coverage", "Diagnosis confidence", "Customer signals"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Customer signals",
    aliases: ["signals", "customer-facing signals"],
    title: "Customer signals",
    subtitle: "Volume of customer-facing evidence behind the diagnosis.",
    purpose: "Customer signals give scale to the issue by counting returns, refunds, negative reviews, and matched return/refund relationship counts that came from customer behavior.",
    whereShown: "Product Detail insight metric cards and evidence sections.",
    valueFormula: "customerSignals = returnUnits + refundUnits + negativeReviewCount + matchedReturnRefundSignalCount",
    supportingFormulas: [
      "negativeReviewPressure = negativeReviewCount / reviewCount",
      "returnPressure = returnedUnits / soldUnits",
      "refundLeakage = refundedUnits / soldUnits",
    ],
    inputs: ["Return units", "Refund units", "Negative review count", "Review count", "Return/refund relationship counts"],
    interpretation: ["A rising line means more customers are generating signals that deserve attention.", "Use it to understand scale, then inspect evidence for root cause."],
    caveats: ["It is a signal count/summary, not a standalone severity formula.", "Multiple signals can come from the same underlying order or customer event."],
    relatedMetrics: ["Return pressure", "Refund leakage", "Negative review pressure", "Evidence strength"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Negative review pressure",
    aliases: ["negative pressure", "review pressure", "negative reviews"],
    title: "Negative review pressure",
    subtitle: "Connected negative reviews as a share of all connected reviews.",
    purpose: "Negative review pressure is an early warning sentiment card. It can reveal quality or expectation issues before operational return/refund data fully appears.",
    whereShown: "Product Detail insight metric cards and scoring explanations.",
    valueFormula: "negativeReviewPressure = negativeReviewRate = negativeReviewCount / reviewCount",
    supportingFormulas: [
      "reviewSignalValue = negativeReviewRate * 0.7 + ratingPressure + samplePressure + criticalPressure + csvRatingRisk * 0.55 + negativeReviewCount * 2",
      "ratingPressure = max(0, 4 - averageRating) * 14",
      "samplePressure = min(18, log2(reviewCount + 1) * 4)",
    ],
    inputs: ["Negative review count", "Total review count", "Average rating", "CSV critical rating count", "CSV rating risk"],
    interpretation: ["Higher pressure means sentiment is worsening or concentrated.", "The Product Detail card uses warning tone at around 12% or more."],
    caveats: ["If review count is zero, ProductPulse treats the rate as 0.", "Risk scoring smooths and caps low samples."],
    relatedMetrics: ["Negative review rate", "Review rating", "Product risk"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Main issue",
    aliases: ["primary issue", "issue category"],
    title: "Main issue",
    subtitle: "The strongest issue category currently detected.",
    purpose: "Main issue explains what ProductPulse believes is driving the diagnosis, such as return pressure, refund leakage, product quality, expectation mismatch, variants, or content gaps.",
    whereShown: "Product Detail insight metric cards and diagnosis summary.",
    valueFormula: "mainIssue = highest weighted issue/category from diagnosis and score component evidence",
    supportingFormulas: [
      "risk components include returns, refunds, reviews, sentiment, content gap, variant concentration, agreement, and recency",
      "diagnosis issue labels come from deterministic evidence plus AI synthesis during deep diagnosis",
    ],
    inputs: ["Risk component weights", "Diagnosis issue labels", "Evidence snippets", "Customer language", "Recommendation context"],
    interpretation: ["Use Main issue to understand the dominant reason behind the score.", "Then inspect evidence before creating or editing app-owned actions."],
    caveats: ["If deep diagnosis has not run, the main issue may be preliminary or missing.", "It is a summary label and may hide several contributing issues."],
    relatedMetrics: ["Product risk", "Evidence strength", "Recommended fix"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "medium",
  },
  {
    found: true,
    cardName: "Recommended fix",
    aliases: ["fix", "suggested fix", "next action"],
    title: "Recommended fix",
    subtitle: "The safest next internal action ProductPulse can recommend from evidence.",
    purpose: "Recommended fix turns the strongest evidence into a practical next step, such as reviewing QA, clarifying product description, adding expectation guidance, improving variant clarity, or dismissing unsupported work.",
    whereShown: "Product Detail insight metric cards and Recommended Actions.",
    valueFormula: "recommendedFix = highest priority supported action derived from diagnosis evidence and ProductAction state",
    supportingFormulas: [
      "action priority uses issue severity, confidence, evidence strength, expected impact, and support rules",
      "ProductPulse internal actions require confirmation before mutation",
    ],
    inputs: ["Main issue", "Diagnosis recommendations", "ProductAction records", "Evidence strength", "Action status"],
    interpretation: ["Treat it as guidance for ProductPulse internal work, not as a Shopify change already performed.", "Use action cards to review details or confirm supported app-only mutations."],
    caveats: ["Unsupported action types should remain unavailable.", "The assistant must not claim a Shopify mutation was applied."],
    relatedMetrics: ["Recommended Actions", "Main issue", "Evidence strength"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Basket Context",
    aliases: ["purchase context", "basket", "co-purchase context", "order context"],
    title: "Basket Context",
    subtitle: "How the product is bought inside Shopify orders: alone, with other products, in quantity, or across variants.",
    purpose: "Basket Context explains whether product outcomes are easier or harder to attribute. A product mostly bought alone gives clearer product attribution; a product often bought with others can introduce refund/return ambiguity unless line-item matching is strong.",
    whereShown: "Product Detail purchase context/basket panel and diagnosis explanations when purchase context is available.",
    valueFormula: "multiProductBasketRate = multiProductOrderCount / totalOrdersContainingProduct",
    supportingFormulas: [
      "soloPurchaseRate = soloProductOrderCount / totalOrdersContainingProduct",
      "bulkPurchaseRate = bulkOrderCount / totalOrdersContainingProduct",
      "multiVariantOrderRate = multiVariantOrderCount / totalOrdersContainingProduct",
      "affinityScore = P(other product | this product) / P(other product)",
    ],
    inputs: ["Order line items", "Order id", "Product id", "Variant id", "Quantity", "Basket line items", "Return/refund attribution"],
    interpretation: [
      "Mostly bought alone can strengthen product-specific attribution when negative signals exist.",
      "Often bought with other products can reduce confidence for weak order-level refunds.",
      "Bulk or multi-variant patterns can support QA, specs, or variant clarity recommendations when return/refund evidence exists.",
    ],
    caveats: [
      "Raw orders are not stored relationally; summaries are persisted in metrics JSON.",
      "Missing line-item or customer context lowers confidence.",
      "Basket context is a modifier, not a separate Product Risk system.",
    ],
    relatedMetrics: ["Return pressure", "Refund leakage", "Relationship lift", "Product relationship timeline"],
    source: PURCHASE_CONTEXT_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Product relationship timeline",
    aliases: ["relationship timeline", "timeline between products", "bought together", "bought before", "bought after"],
    title: "Product relationship timeline",
    subtitle: "Products bought with, before, or after the current product.",
    purpose: "The relationship timeline shows same-order and customer-sequence affinities so merchants can see products that travel with the current product in baskets or purchase journeys.",
    whereShown: "Product Detail product relationships panel.",
    valueFormula: "sameOrderLift = attachRate / relatedProductBaseRate; beforeAfterLift = relationshipRate / customerBaseRateOfRelatedProduct",
    supportingFormulas: [
      "attachRate = orders_with_A_and_B / orders_with_A",
      "relatedProductBaseRate = orders_with_B / total_known_basket_orders",
      "relationshipRate = customers_who_bought_B_in_window / customers_who_bought_A",
      "customerBaseRateOfRelatedProduct = customers_who_bought_B / total_known_customers",
      "timeline buckets: 0-7 days, 8-30 days, 30+ days",
    ],
    inputs: ["Basket line items", "Order ids", "Customer key when available", "Purchase dates", "Related product catalog mapping", "Return/refund impact deltas"],
    interpretation: [
      "Together means same Shopify order.",
      "Before means customers bought the related product before this product.",
      "After means customers bought the related product after this product.",
      "Higher rate, higher lift, larger sample, and higher confidence make a relationship more useful.",
    ],
    caveats: [
      "Previous/next relationships require a safe customer key; without it they are unavailable.",
      "Relationship metrics are observational, not causal.",
      "Large baskets and deleted products can reduce confidence.",
    ],
    relatedMetrics: ["Lift", "Attach rate", "Relationship rate", "Relationship strength", "Relationship confidence"],
    source: RELATIONSHIP_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Return & refund resolution",
    aliases: ["returns vs refunds relationship", "return refund relationship", "return and refund resolution"],
    title: "Return & refund resolution",
    subtitle: "Whether product friction became confirmed financial loss, stayed return-only, or remained unattributed.",
    purpose: "This card separates returned-and-refunded units, return-only cases, refund-only cases, exchanges/replacements, pending/unknown cases, and unattributed refunds. It helps explain attribution quality before blaming the product for money loss.",
    whereShown: "Product Detail return/refund resolution panel and evidence sections.",
    valueFormula: "linkedPercent = returnedAndRefundedUnits / returnedUnits",
    supportingFormulas: [
      "returnOnlyPercent = returnedNotRefundedUnits / returnedUnits",
      "refundOnlyPercent = refundedWithoutReturnUnits / max(refundedUnits, returnedAndRefundedUnits + refundedWithoutReturnUnits)",
      "bucketWidth = bucketValue / totalResolvedBuckets",
    ],
    inputs: ["Returned units", "Refunded units", "Returned and refunded units", "Return-only units", "Refund-only units", "Exchange/replacement units", "Pending/unknown count"],
    interpretation: ["Linked return+refund is stronger product-attributed financial loss.", "Return-only means friction may be exchange, pending, or replacement.", "Refund-only and unattributed refund cases need careful attribution."],
    caveats: ["Attribution confidence depends on line-item matching.", "Order-level unattributed refunds in multi-product baskets must not be used as pair-level impact."],
    relatedMetrics: ["Return pressure", "Refund leakage", "Financial exposure", "Diagnosis confidence"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Return rate",
    aliases: ["rate return", "returns rate"],
    title: "Return rate",
    subtitle: "Returned units as a share of sold units.",
    purpose: "Return rate is the simplest visible measure of product return friction in the analysis window.",
    whereShown: "Product Detail metrics, evidence cards, dashboard/product cards, and scoring explanations.",
    valueFormula: "returnRate = roundPercent(returnUnits / soldUnits)",
    supportingFormulas: ["roundPercent(rate) = round(rate * 1000) / 10"],
    inputs: ["Return units", "Sold units"],
    interpretation: ["Higher return rate increases risk only when sample support and baseline comparison justify it.", "It is visible friction, not money leakage."],
    caveats: ["If sold units are zero, ProductPulse stores 0.", "Risk scoring uses smoothed/baseline-aware return pressure, not only the displayed percentage."],
    relatedMetrics: ["Return pressure", "Product risk"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Refund rate",
    aliases: ["rate refund", "refunds rate"],
    title: "Refund rate",
    subtitle: "Refunded units as a share of sold units.",
    purpose: "Refund rate is the simplest visible measure of how often sold units turned into refunds in the analysis window.",
    whereShown: "Product Detail metrics, evidence cards, dashboard/product cards, and scoring explanations.",
    valueFormula: "refundRate = roundPercent(refundUnits / soldUnits)",
    supportingFormulas: ["roundPercent(rate) = round(rate * 1000) / 10"],
    inputs: ["Refund units", "Sold units"],
    interpretation: ["Higher refund rate can increase refund risk and financial exposure.", "It should be read with refund amount and attribution confidence."],
    caveats: ["If sold units are zero, ProductPulse stores 0.", "Refund amount can matter even when refund rate is moderate."],
    relatedMetrics: ["Refund leakage", "Financial exposure"],
    source: SCORING_SOURCE,
    confidence: "high",
  },
  {
    found: true,
    cardName: "Monthly order activity",
    aliases: ["order activity", "monthly activity", "commercial charts"],
    title: "Monthly order activity",
    subtitle: "Order, return, refund, revenue, and unresolved return cohorts by month.",
    purpose: "Monthly order activity is a deep-diagnosis chart that shows how product demand and post-purchase outcomes move across cohort months.",
    whereShown: "Product Detail deep research section after full diagnosis.",
    valueFormula: "monthlyActivity = group orders, returned order cohorts, refunded order cohorts, revenue, and unresolved returns by cohort month",
    supportingFormulas: [
      "return cohort count = returned orders in month cohort",
      "refund cohort count = refunded orders in month cohort",
      "unresolved returns = opened returns - resolved returns when available",
    ],
    inputs: ["Monthly order cohorts", "Returned orders", "Refunded orders", "Revenue", "Unresolved return events"],
    interpretation: ["Read demand and friction together: rising orders with rising returns may mean growth with quality pressure.", "Revenue line gives commercial context to the order/return bars."],
    caveats: ["Requires deep diagnosis and stored order evidence.", "No activity appears until enough Shopify order data is available."],
    relatedMetrics: ["Return rate", "Refund rate", "Financial exposure"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "medium",
  },
  {
    found: true,
    cardName: "Return rate prediction",
    aliases: ["prediction model", "return prediction", "forecast return rate"],
    title: "Return rate prediction",
    subtitle: "Weekly return-rate cohorts projected three months forward.",
    purpose: "Return rate prediction smooths observed weekly Shopify order cohorts and projects near-term return behavior. The forecast range widens as uncertainty grows.",
    whereShown: "Product Detail prediction model section after full diagnosis.",
    valueFormula: "forecastNext90ReturnRate = smoothed observed return-rate trend projected over the next 90 days",
    supportingFormulas: [
      "totalReturnRate = totalReturnedUnits / totalOrderUnits",
      "last60DayReturnRate = returned units in last 60 days / order units in last 60 days",
      "last30DayReturnRate = returned units in last 30 days / order units in last 30 days",
    ],
    inputs: ["Weekly order cohorts", "Returned orders/units", "Observed return rates", "Forecast points", "Action adjustment"],
    interpretation: ["Use observed data for what happened and the forecast range for uncertainty.", "The next-three-month value is a projection, not a guarantee."],
    caveats: ["Requires deep diagnosis and stored order/return data.", "Prediction is separate from Product Momentum."],
    relatedMetrics: ["Return pressure", "Return rate", "Financial exposure"],
    source: PRODUCT_DETAIL_CARD_SOURCE,
    confidence: "medium",
  },
];
